### ISSUE TITLE
Implement properly

### ISSUE THREAD

**Issue by bill-myers** [taiki-e/replace-await#1]
First of all, the use of insert into a Vec is terrible since it makes the runtime O(n^2).

Second, this must be done by properly parsing the syntax (either with an AST or with at least a complete lexer) since the current approach is broken (e.g. it will mangle string literals containing "await!(x)").

**Comment by taiki-e** [comment]
> First of all, the use of insert into a Vec is terrible since it makes the runtime O(n^2).

Thanks for pointing that out.

> Second, this must be done by properly parsing the syntax (either with an AST or with at least a complete lexer) since the current approach is broken (e.g. it will mangle string literals containing "await!(x)").

This is intentional. This tool is intended to replace not only code but also macros in the document. AFAIK use cases that want to maintain outdated `await` macro in documents and literals are rare.
